config/routes.rb
Rails.application.routes.draw do
  get 'errors/404'
  get 		'sessions/new'
  root 		'home#index'
  get 		'users/new'
  get     'edit',       to: 'users#edit'
  post    'edit',       to: 'users#update' 
  get     'users',      to: 'users#index'
  get 		'/signup',		to: 'users#new'
  post 		'/signup',		to: 'users#create'
  get 		'/login',		  to: 'sessions#new'
  post 		'/login',		  to: 'sessions#create'
  get 	'/logout',		to: 'sessions#destroy'
  get 'messages',       to: 'conversations#index'
  get 'inbox',			to: 'conversations#inbox'
  get 'conversations',	to: 'conversations#create'

  # for elasticsearch/searchkick
  #get 'search',         to: 'search#search'

  resources :users
  resources :books
  resources :account_activations, only: [:edit]
  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    member do
      delete :delete_cover_image
      delete :delete_condition_image
    end
  end

  resources :books do
    collection do
      get :autocomplete 
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :activation_token
	has_many :books, dependent: :destroy
	before_save :downcase_email
	before_create :create_activation_digest
	validates :fname, presence: true, length: { maximum: 50 }
	validates :lname, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.edu+\z/i
	validates :email, presence: true, length: { maximum: 255 }, 
		format: { with: VALID_EMAIL_REGEX },
		uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, :if => :password

	mount_uploader :image, ImageUploader

	# Returns the hash digest of the given string.
	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		                                              BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	# Returns a random token.
	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def activate
		update_columns(activated: true, activated_at: Time.zone.now)
	end

	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	# Returns true if the given token matches the digest.
	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	private
		def downcase_email
			self.email = email.downcase
		end

		def create_activation_digest
			self.activation_token = User.new_token
			self.activation_digest = User.digest(activation_token)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]

  def index
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    redirect_to root_url and return unless @user.activated?
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      @user.send_activation_email
  		flash[:success] = "Please confirm your e-mail address."
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def edit
    if current_user.id != @user.id
      redirect_to root_url
    else
      @emailAlert = false
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      @emailAlert = true
      render 'edit'
    end
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:fname, :lname, :email, :password, :password_confirmation, :image, :remove_image)
  end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
    <div class="float-right">
        <%= link_to "Log out", logout_path, method: :delete, class: "btn btn-success" %>
    </div>

    <div class="row my-3">
        <div class="col-auto my-3">
            <%=image_tag(@user.image.medium.url == nil ? "fallback/userImgDefault.png" : @user.image.medium.url, alt: "Example Image", alt: "@user.fname user.lname", class: "rounded-circle m-3", style: "height: 150px; width: 150px;")%>
            <h2 class="text-capitalize my-3"> <%= @user.fname + " " + @user.lname %> </h2>
        </div>

        <%= form_for @user do |f| %>
            <%= render 'shared/error_messages' %>
        <div class="col p-5">
            <div class="card">
                <div class="card-header font-weight-bold">
                    Basic Info
                </div>
                <div class="card-body">
                    <p class="card-text my-1">   
                        <table class="table table-borderless">
                            <tbody>

                                <% if !@emailAlert %>
                                    <tr>
                                        <div class="form-group">
                                            <th scope="row"></th>
                                            <td>
                                                <small style="color:red">
                                                    <strong>
                                                        NOTE: Email cannot be changed after it has been set
                                                    </strong>
                                                </small>
                                            </td>
                                        </div>
                                    </tr>
                                <% end %>
                                
                                <tr>
                                    <div class="form-group">
                                        <th scope="row"><%= f.label :"First Name" %></th>
                                        <td><%= f.text_field :fname, class: "form-control", placeholder: "First Name", id: "firstName" %></td>
                                    </div>
                                </tr>
                                
                                <tr>
                                    <div class="form-group">
                                        <th scope="row"><%= f.label :"Last Name" %></th>
                                        <td><%= f.text_field :lname, class: "form-control", placeholder: "Last Name", id: "lastName" %></td>
                                    </div>
                                </tr>

                                <tr>
                                    <div class="form-group">         
                                        <th scope="row"><%= f.label :image %></th>
                                        <td style="color:grey">
                                            <%= f.file_field :image %>
                                            <% if f.object.image? %>
                                                <small>
                                                    <%= f.label :remove_image %>
                                                </small>
                                                <%= f.check_box :remove_image %> 
                                            <% end %>                                                              
                                        </td>
                                    </div>  
                                </tr>

                                <tr>
                                    <div class="form-group">
                                        <th scope="row" style="color:grey"><%= f.label :"Email" %></th>
                                        <td style="color:grey"><%= @user.email %></td>
                                    </div>
                                </tr>

                                <tr id="pwdButton">
                                    <div class="form-group">
                                        <th scope="row"></th>
                                        <td>
                                            <button type ="button" class="btn btn-link" data-toggle="modal" data-target="#pwdModal">
                                                Reset Password
                                            </button>
                                        </td>
                                    </div>
                                </tr>

                            </tbody>
                        </table>   
                    </p>
                </div>
            </div>
        </div>

        <div class="modal fade" id="pwdModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog  modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">
                            Password Reset
                        </h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    <div class="modal-body">    
                        <div style="margin-top:1%">
                        </div>        
                        <table class="table table-borderless">
                            <tbody>  
                                <tr>
                                    <div class="form-group">
                                        <th scope="row"><%= f.label :"Password" %></th>
                                        <td><%= f.password_field :password, class: "form-control", placeholder: "Password" , id: "pwd" %></td>
                                    </div>
                                </tr>

                                <tr>
                                    <div class="form-group">
                                        <th scope="row"><%= f.label :"Confirm Password" %></th>
                                        <td><%= f.password_field :password, class: "form-control", placeholder: "Confirm Password", id: "pwdValidation" %></td>
                                    </div>
                                </tr>
                            </tbody>
                        </table>   
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" onClick="clearUserPasswordFields()">Clear</button>
                        <%= f.submit "Edit My Account", class: "btn btn-primary" %>
                    </div>
                </div>
            </div>
        </div>

        <%= f.submit "Edit My Account", class: "btn btn-lg btn-primary btn-block bottomPart" %>
        <% end %>  
    
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col">
			<% content_for(:title, 'All Users') %>
			<h1 class="mt-3">Users</h1>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<table class="table text-center">
				<thead class="bg-secondary text-white">
					<tr>
						<th scope="col">First Name</th>
						<th scope="col">Last Name</th>
						<th scope="col">Link</th>
					</tr>
				</thead>
				<tbody class="">
					<% @users.each do |user| %>
							<tr>
								<th scope="row"><%= user.fname %></th>
								<td><%= user.lname %></td>
								<td><%= link_to "View Profile", user, class: "btn btn-sm btn-primary"%></td>
								<br>
							</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row outerAligned">
    <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12 aligned">
      <h1 class="h3 mb-3 font-weight-normal text-center text-top">Sign up</h1>

      <%= form_for @user do |f| %>
        <%= render 'shared/error_messages' %>

        <div class="form-group">
          <%= f.label :fname, "First Name" %>
          <%= f.text_field :fname, class: 'form-control', placeholder: "First Name" %>
        </div>
        <div class="form-group">
          <%= f.label :lname, "Last Name" %>
          <%= f.text_field :lname, class: 'form-control', placeholder: "Last Name" %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control', placeholder: "Email" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control', placeholder: "Password" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Confirm Password" %>
          <%= f.password_field :password, class: 'form-control', placeholder: "Confirm Password"%>
        </div>
        <%= f.submit "Create my account", class: "btn btn-md btn-primary btn-block bottomPart" %>
      <% end %>

    </div>
  </div>
</div>

<!--<div class="row outerAligned">
  <div class="col-lg-4 col-md-6 col-sm-8 col-xs-12 aligned">
<% provide(:title, 'Sign up') %>
<h1 class="h3 mb-3 font-weight-normal text-center text-top">Sign up</h1>




<form class="form-signin">
  <%= form_for(@user, url: signup_path) do |f| %>
    <%= render 'shared/error_messages' %>

  <div class="form-group">
    <%= f.label :"First Name" %>
    <%= f.text_field :fname, class: 'form-control', placeholder: "First Name" %>
</div>
    <br>
<div class="form-group">
    <%= f.label :"Last Name" %>
    <%= f.text_field :lname, class: 'form-control', placeholder: "Last Name" %>
</div>
    <br>
<div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control', placeholder: "Email" %>
</div>
    <br>
<div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control', placeholder: "Password" %>
</div>
    <br>
<div class="form-group">
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Confirmation"%>
</div>
    <br>
    <%= f.submit "Create my account", class: "btn btn-lg btn-primary btn-block bottomPart" %>
  <% end %>
</form>

</div>
</div>-->

app/views/users/show.html.erb
<% provide(:title, @user.fname + ' ' + @user.lname) %>
<div class="container">
	<div class="row my-3">
		<div class="col-auto my-3">
			<%=image_tag(@user.image.medium.url, alt: "Example Image", alt: "@user.fname user.lname", class: "rounded-circle m-3", style: "height: 150px; width: 150px;")%>
			<h2 class="text-capitalize my-3"> <%= @user.fname + " " + @user.lname %> </h2>
		</div>
		<div class="col p-5">
			<div class="card">
				<div class="card-header font-weight-bold">
					Basic Info
				</div>
				<div class="card-body">
					<p class="card-text my-1">
						<table class="table table-borderless">
							<tbody>
								<tr>
									<th scope="row">First Name</th>
									<td><%= @user.fname %></td>
								</tr>
								<tr>
									<th scope="row">Last Name</th>
									<td><%= @user.lname %></td>
								</tr>
								<tr>
									<th scope="row">Email</th>
									<td><%= @user.email %></td>
								</tr>
									<% if current_user.id == @user.id %>
										<tr>
											<th scope="row">ID Number: </th>
											<td><%= @user.id %></td>
										</tr>
										<tr>
											<th scope="row"></th>
											<td> 
												<div>
													<%= link_to "Edit User", edit_user_path %> 
												</div>
											</td>
										</tr>
										<tr>
											<th scope="row"></th>
											<td> 
												<div>
													<%= link_to "Log out", logout_path, method: :delete %>
												</div>
											</td>
										</tr>
									<% end %>
							</tbody>
						</table>
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col">
			<div id="accordion">
				<div class="card">
					<div class="card-header" id="headingOne">
						<h5 class="mb-0">
						<button class="btn w-100" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
							<h4 class="font-weight-bold my-0 text-success">
							Books
						</h4>
					    </button>
					    </h5>
					</div>
					<div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
						<% @user.books.each do |book| %>
					      	<div class="card-body m-2">
					      		<div class="row">
					      			<div class="col-auto">
					      				<% if book.cover_image.attached? %>
					      					<%= image_tag book.cover_image.variant(resize: "200x300") %>
					      				<% else %>
					      					<%= image_tag("fallback/book/medium_default.png") %>
					      				<% end %>

					      			</div>
					      			<div class="col-auto">
					      				<span class="text-capitalize font-weight-bold h3"><%= book.title %></span> 
					      				<br/>
							        	AUTHOR: <%= book.author %> <br/>
							        	ISBN-13: <%= book.isbn13 %> <br/>
							        	ISBN-10: <%= book.isbn10 %> <br/>
							        	PRICE: $<%= number_with_precision(book.price, :precision => 2) %> <br/>
							       		<span class="align-bottom align-text-bottom">
							       			<%= link_to  "View", book, class: "btn btn-primary"%>
							       		</span>
					      			</div>
					      		</div>
					   		</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>