config/routes.rb
Rails.application.routes.draw do
  get 'errors/404'
  get 		'sessions/new'
  root 		'home#index'
  get 		'users/new'
  get     'edit',       to: 'users#edit'
  post    'edit',       to: 'users#update' 
  get     'users',      to: 'users#index'
  get 		'/signup',		to: 'users#new'
  post 		'/signup',		to: 'users#create'
  get 		'/login',		  to: 'sessions#new'
  post 		'/login',		  to: 'sessions#create'
  get 	'/logout',		to: 'sessions#destroy'
  get 'messages',       to: 'conversations#index'
  get 'inbox',			to: 'conversations#inbox'
  get 'conversations',	to: 'conversations#create'

  # for elasticsearch/searchkick
  #get 'search',         to: 'search#search'

  resources :users
  resources :books
  resources :account_activations, only: [:edit]
  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    member do
      delete :delete_cover_image
      delete :delete_condition_image
    end
  end

  resources :books do
    collection do
      get :autocomplete 
    end
  end
end

app/models/book.rb
# require 'elasticsearch/model'
class Book < ApplicationRecord
	#required for searchkick, uncomment when needed/ready
	#searchkick word_start: [:title, :author, :description, :isbn13, :isbn10]

	#for elasticsearch
#	include Elasticsearch::Model
# 	include Elasticsearch::Model::Callbacks

	validates :isbn13, :isbn_format => true , length: { is: 13 }
	# validates :isbn10, :isbn_format => { :with => :isbn10 }
	validates :isbn13, :isbn_format => { :with => :isbn13 }	
	validates :title, presence: true
    validates :author, presence: true
    validates :price, presence: true, numericality: { greater_than: 0}
    validates :condition, presence: true
    validates :description, presence: true
	belongs_to :user

	#added for search kick, uncomment when ready/needed
#	def search_data
#		{
#			title: title, 
#			author: author, 
#			description: description, 
#			isbn13: isbn13, 
#			isbn10: isbn10
#		}
#	end


	#attr_accessor :state_event, :remove_cover_image

	#after_save :trigger_state, if: :state_event
	private def trigger_state
		send(state_event) if send(:"can_#{state_event}?")
	end

	#after_save :purge_cover_image, if: :remove_cover_image
	private def purge_cover_image
		cover_image.purge
	end

	# active_storage for multiple images
	has_one_attached :cover_image
	has_many_attached :condition_images

	#copied from https://code.tutsplus.com/tutorials/rails-image-upload-using-carrierwave-in-a-rails-app--cms-25183
	#allows to upload an image

	mount_uploader :image, ImageUploader

	#needed for regular search, uncomment if needed
	def self.search(search)
		if search
			where('title LIKE ? OR author LIKE ? OR isbn13 LIKE ? OR isbn10 LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
		else
			all
		end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :find_book, only: [:show, :edit, :update, :destroy]
# before_action :default_image, only: [:show, :edit, :update, :destroy]
# before_action :image_nil, only: [:show, :edit, :update, :destroy]


  helper_method :sort_column, :sort_direction


  #currently sorts and paginates at 3 books per page
  def index
# required for searchkick
#    term = params[:search].present? ? params[:search] : nil

  	@books = Book.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 5)
    
    #search kick if statement for search. issues with order and paginate
#    @books = if term
#      Book.search(term).order("LOWER(" + sort_column + ") " + sort_direction).paginate(:page => params[:page], :per_page => 5)
#    else
#      Book.all.order("LOWER(" + sort_column + ") " + sort_direction).paginate(:page => params[:page], :per_page => 5)
#    end
  end

  def new
  	@book = Book.new
  end

  def create
    @book = Book.new(post_params)
  	if @book.save
  		redirect_to @book
  	else
      flash.now['danger'] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def show
  	#@book = Book.find(params[:id])
  end

  def edit
  	#@book = Book.find(params[:id])
  end

  def update
    if current_user.id = @book.user_id
    	if @book.update(post_params)
    		redirect_to @book
    	else
    		render 'edit'
      end
    else
      flash.now['danger'] = "This post does not belong to you."
  	end
  end
  
  def destroy
    if current_user.id = @book.user_id
    	@book.destroy
    	redirect_to root_path
    else
      flash.now['danger'] = "This post does not belong to you."
    end
  end

  def delete_image_attachment
    @book.cover_image = ActiveStorage::Blob.find_signed(params[:id])
    @book.cover_image.purge 
    redirect_to listing_space_path(@space)
  end

  def delete_cover_image
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge # or use purge_later
    redirect_back(fallback_location: books_path)
  end

  def delete_condition_image
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge # or use purge_later
    redirect_back(fallback_location: books_path)
  end

  def autocomplete
    render json: Book.search(params[:query], {
      fields: ["title^5", "author", "description", "isbn13", "isbn10"],
      match: :word_start,
      limit: 10,
      load: false,
      misspellings: {below: 5}
    }).map(&:title)
  end

  private
  def sort_column
    Book.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  #accessor method and validation for the direction
  #used to prevent SQL injection and setting asc as default value
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def find_book
  	@book = Book.find(params[:id])
  end

  def post_params
  	params.require(:book).permit(:title, :author, :isbn13, :isbn10, :price, :user_id, :image, :remove_cover_image, :condition, :description, :cover_image, condition_images: [])
  end

  #assigns default image if user did not upload an image for book
  def default_image
    if @book.image == nil
      @book.image = "userImgDefault.png"
    end
  end

  def image_nil
    @book = Book.find(params[:id])
     if !@book.cover_image.attached?
         @book.cover_image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'fallback', 'default.png')), filename: 'default.png', content_type: 'image/png')
     end
  end  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div class="alert alert-danger" role="alert" id="unableToFill" style="display:none;text-align:center">
  	<strong>
  		Invalid ISBN, unable to auto-fill
	</strong>
</div>
<div class="row outerAligned">
  	<div class="col-lg-7 col-md-7 col-sm-10 col-xs-12 aligned">
	  	<div style="margin-top:1%">
			<span>
				<button type ="button" class="btn btn-primary" onClick="connectToBookAPI()">
					<strong>Auto-fill</strong>
				</button>
				<button type ="button" class="btn btn-primary" onClick="clearAllBookFields()">
					<strong>Clear All</strong>
				</button>
			</span>
		</div>
		<%= form_for @book do |f| %>

		  	<!-- Title Form Item -->
			<div class="form-group">
				<%= f.label :title %><br/>
				<%= f.text_field :title, class: 'form-control', placeholder: "Title", id: "title" %>
			</div>

			<!-- Author Form Item -->
			<div class="form-group">
				<%= f.label :"author(s)" %><br/>
				<%= f.text_field :author, class: 'form-control', placeholder: "Author(s) - separate multiple with a comma", id: "author" %>
			</div>

			<!-- ISBN Form Item -->
			<div class="form-group">
				<%= f.label :isbn13 %><br/>
				<%= f.text_field :isbn13, class: 'form-control', placeholder: "ISBN-13", id: "isbn13" %>
			</div>

			<div class="form-group">
				<%= f.label :isbn10 %><br/>
				<%= f.text_field :isbn10, class: 'form-control', placeholder: "ISBN-10", id: "isbn10" %>
			</div>

			<!--Adding drop down for book condition -->
			<div class="form-group">
				<%= f.label :condition %><br/>
				<%= f.select(:condition, options_for_select({'Like New' => 'Like New', 'Good' => 'Good', 'Acceptable' => 'Acceptable'}, @book.condition), {:include_blank => "Select Condition"})  %>
			</div>


			<!-- Price Form Item-->
			<div class="form-group">
				<%= f.label :price %><br/>
				<%= f.text_field :price, class: 'form-control', placeholder: "Price", id: "price" %>
			</div>

		  	<!------------------------------- NEW Image Form Item -->
		  	<div class="form-group">
			    <strong> <%= f.label :cover_image %>: </strong>
			    <%= f.file_field :cover_image %>
			    <% if @book.cover_image.attached? %>
			    	<br />
			    	<%= image_tag @book.cover_image.variant(resize: "100x150") %>
			    	<%= link_to 'Remove', delete_cover_image_book_url(id: @book.cover_image.id), method: :delete, data: { confirm: 'Are you sure?' } %>
			    	<br />
			    <% end %>
		  	</div>

		  	<!-------------------------------- For Multiple Images -->
		  	<div class="form-group">
			    <strong> <%= f.label :condition_images %>: </strong>
			    <%= f.file_field :condition_images, multiple: true %>
					<% if @book.condition_images.attached? %>
						<% @book.condition_images.each do |condition_image| %>
			    			<br />
			    			<%= image_tag condition_image.variant(resize: "100x150") %>
			    			<%= link_to 'Remove', delete_condition_image_book_url(id: condition_image.id), method: :delete, data: { confirm: 'Are you sure?' } %>
			    			<br />
			    		<% end %>
			    	<% end %>
		  	</div>

			<!--Adding a Text Description Area -->	
			<div class="form-group">
				<%= f.label :description %><br/>
				<%= f.text_area :description, class: 'form-control', placeholder: "Describe your textbook", id: "description" %>
			</div>

			<%= f.hidden_field :user_id, :value => current_user.id %>
			<div class="alignedBtn">
				<%= f.submit "Post Book", class: "btn btn-lg btn-success bottomPart alignedBtn" %>
			</div>
		<% end %>

	</div>

	
</div>

app/views/books/_new_form.html.erb
<div class="alert alert-danger" role="alert" id="unableToFill" style="display:none;text-align:center">
  	<strong>
  		Invalid ISBN, unable to auto-fill
	</strong>
</div>
<div class="row outerAligned">
  	<div class="col-lg-7 col-md-7 col-sm-10 col-xs-12 aligned">
	  	<div style="margin-top:1%">
			<span>
				<button type ="button" class="btn btn-primary" onClick="connectToBookAPI()">
					<strong>Auto-fill</strong>
				</button>
				<button type ="button" class="btn btn-primary" onClick="clearAllBookFields()">
					<strong>Clear All</strong>
				</button>
			</span>
		</div>
		<%= form_for @book do |f| %>

		  	<!-- Title Form Item -->
			<div class="form-group">
				<%= f.label :title %><br/>
				<%= f.text_field :title, class: 'form-control', placeholder: "Title", id: "title" %>
			</div>

			<!-- Author Form Item -->
			<div class="form-group">
				<%= f.label :"author(s)" %><br/>
				<%= f.text_field :author, class: 'form-control', placeholder: "Author(s) - separate multiple with a comma", id: "author" %>
			</div>

			<!-- ISBN Form Item -->
			<div class="form-group">
				<%= f.label :isbn13 %><br/>
				<%= f.text_field :isbn13, class: 'form-control', placeholder: "ISBN-13", id: "isbn13" %>
			</div>

			<div class="form-group">
				<%= f.label :isbn10 %><br/>
				<%= f.text_field :isbn10, class: 'form-control', placeholder: "ISBN-10", id: "isbn10" %>
			</div>

			<!--Adding drop down for book condition -->
			<div class="form-group">
				<%= f.label :condition %><br/>
				<%= f.select(:condition, options_for_select({'Like New' => 'Like New', 'Good' => 'Good', 'Acceptable' => 'Acceptable'}, @book.condition), {:include_blank => "Select Condition"})  %>
			</div>


			<!-- Price Form Item-->
			<div class="form-group">
				<%= f.label :price %><br/>
				<%= f.text_field :price, class: 'form-control', placeholder: "Price", id: "price" %>
			</div>

		  	<!------------------------------- NEW Image Form Item -->
		  	<div class="form-group">
			    <strong> <%= f.label :cover_image %>: </strong>
			    <%= f.file_field :cover_image %>
		  	</div>

		  	<!-------------------------------- For Multiple Images -->
		  	<div class="form-group">
			    <strong> <%= f.label :condition_images %>: </strong>
			    <%= f.file_field :condition_images, multiple: true %>
		  	</div>

			<!--Adding a Text Description Area -->	
			<div class="form-group">
				<%= f.label :description %><br/>
				<%= f.text_area :description, class: 'form-control', placeholder: "Describe your textbook", id: "description" %>
			</div>

			<%= f.hidden_field :user_id, :value => current_user.id %>
			<div class="alignedBtn">
				<%= f.submit "Post Book", class: "btn btn-lg btn-success bottomPart alignedBtn" %>
			</div>
		<% end %>

	</div>

	
</div>

app/views/books/edit.html.erb
<% provide(:title, 'Edit ' + @book.title) %>
<h1>Edit <%= @book.title %></h1>

<%= render 'shared/book_error' %>
<%= render 'form' %>

app/views/books/index.html.erb
<div class="container">
	<div class="row mt-3">
		<div class="col">
			<div class="page-header">
	  			<h1>All Listings</h1>
			</div>
		</div>
		<% if logged_in? %>
			<div class="col mt-1 text-right">
				<%= link_to "Post a Book", new_book_path, class: "btn btn-success btn-lg float-right mr-3" %>
			</div>
		<% end %>
	</div>
 	<div class="d-flex justify-content-center align-content-center">
		<%= will_paginate @books, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
	</div>
	<div class="row">
		<div class="col">
			<table class="table text-center">
				<thead class="link-light">
					<tr class="bg-secondary text-white">
						<th scope="col" style="width: 100px">Thumbnail</th>
						<th scope="col" style="width: 200px">
							<%= sortable "title"%>
						</th>
						<th scope="col" style="width: 200px">
							<%= sortable "author" %>
						</th>
						<th scope="col" style="width: 200px">
							<%= sortable "isbn" %>
						</th>
						<th scope="col" style="width: 100px">
							<%= sortable "condition" %>
						</th>
						<th scope="col" style="width: 100px">
							<%= sortable "price" %>
						</th>
						<th scope="col" style="width: 100px">
							Purchase
						</th>
					</tr>
				</thead>
				<tbody>
					<% @books.each do |book| %>
						<tr>
							<td class="text-center">
								<% if book.cover_image.attached? %>
									<%= image_tag book.cover_image.variant(resize: "50x50") %>
								<% else %>
									<%= image_tag("fallback/book/thumb_default.png") %>
								<% end %>
							</td>
							<td><%= book.title %></th>
							<td><%= book.author %></td>
							<td><%= book.isbn13 %></td>
							<td><%= book.condition %></td>
							<td>$<%= number_with_precision(book.price, :precision => 2) %></td>
							<% if logged_in? %>
								<td>
									<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#bookModal<%= book.id %>">
										Quick View
									</button>

									<!-- MODAL for BOOK -->
									<div class="modal fade" id="bookModal<%= book.id %>" aria-labelledby="exampleModalLabel" aria-hidden="true">
									 	<div class="modal-dialog modal-lg" role="document">
									    	<div class="modal-content">
									      		<div class="modal-header text-center" style="background-color: #456173; color: white;">
										        		<h5 class="modal-title" id="exampleModalLabel">
										        			<div class="modalTitle">
										        				<strong><%= book.title %></strong>
										        				<span style="font-size: 10px; width: 200px;"> 
										        					by <%= book.author%>
										        				</span>
										        			</div> 
										        		</h5>
											        	<button type="button" class="close" data-dismiss="modal" aria-label="Close">
											          	<span aria-hidden="false">&times;</span>
											        	</button>
									      		</div>
									     		<div class="modal-body">
									     			<div class="container-fluid">
										      			<div class="row">
										      				<div class="col-sm-6">
										      					<% if book.cover_image.attached? %>
																	<%= image_tag book.cover_image.variant(resize: "200x300") %>
																<% else %>
																	<%= image_tag("fallback/book/medium_default.png") %>
																<% end %>
										      				</div>
										      				<div class="col text-left">
										      					<strong>Title:</strong> <%= book.title %><br/>
										      					<strong>Author:</strong> <%= book.author %><br/>
										      					<strong>ISBN-13:</strong> <%= book.isbn13 %><br/>
										      					<strong>ISBN-10:</strong> <%= book.isbn10 %><br/>
										      					<strong>Condition:</strong> <%= book.condition %><br/>
										      					<strong>Price:</strong> $<%= number_with_precision(book.price, :precision => 2) %>
										      				</div>
										      			</div>
											      	</div>
										    		</div>
											    <div class="modal-footer">
											    	<%= link_to  "View", book, class: "btn btn-primary"%>
											    	<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
											    </div>
									    	</div>
									  	</div>
									</div>

								</td>
							<% else %>

								<!-- MODAL LOGIN Button-->
								<td> 
									<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#signInModal">
										Log In
									</button>
								 </td>

							<% end %> <br>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<div class="d-flex justify-content-center align-content-center">
		<%= will_paginate @books, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>
	</div>
</div>

app/views/books/new.html.erb
<% provide(:title, 'New Post') %>
<h1>List New Book</h1>

<%= render 'shared/book_error' %>
<% if logged_in? %>
	<%= render 'new_form' %>
<% else %>
	<% flash.now['danger'] = "You must be logged in to create a new post." %>
<% end %>

app/views/books/show.html.erb
<script>

//the function that changes out the bigger picture on hover. It adds the mouseover event listener twice.
//onMouseOver, it uses the context sensitive "this" to extract the img src attribute from which it'll use to swap out with the bigger picture's swap attribute.
//then the width is resized appropriately
	function changeImage(){

		$(".clickImage img").mouseover(function(){
			var toChange = $(this).attr("src");
			$("#bookView img").attr("src", toChange);
			$("#bookView img").css("width", "200");
		});


	}

</script>
<% provide(:title, @book.title) %>
<div class="container pb-4 text-left">
	<div class="row title">
		<div class="col my-3">
			<h1>
				<span class="no-gutters">
					<%= @book.title %>
				</span>
				<span class="text-muted lead" style="font-size: .4em;">
					by <%= @book.author %>
				</span>
				<span class="p-1 float-right text-success border border-success rounded bg-light">
					$ <%= @book.price %>
				</span>
			</h1>
		</div>
	</div>
	<div class="row">

		<!-- New Thumbnail -->
		<div class="col-xl-3 col-lg-4 col-md-5 pl-5 ml-4 picturesView">
			<!-- frame is for the purpose of aligning the bigger picture -->
			<div id="frame">
				<!-- bookView is the placeholder for where other images will appear in on hover -->
			<div id="bookView">
				<% if @book.cover_image.attached? %>
					<%= image_tag @book.cover_image.variant(resize: "200x300"), class:"coverImage" %><br/>
				<% else %>
					<%= image_tag("fallback/book/medium_default.png") %>
				<% end %>
			</div>
		</div>
		<span class="lead" style="font-size: 1.15em;">Other Book Pictures: </span>
		<div class="clickImage">
			<% if @book.condition_images.attached? %>
				<!-- the main book cover which can come back on mouse over -->
				<% if @book.cover_image.attached? %>
					<%= link_to image_tag(@book.cover_image, width: "70"), @book.cover_image, onmouseover: "changeImage()", class: "picture" %>
				<% else %>
					<%= image_tag("fallback/book/thumb_default.png") %>
				<% end %>
				<!-- the for loop pulls out and lays out all the uploaded book photos. Onmouseover it displays the larger version of the book photo and puts it into bookView -->
				<% @book.condition_images.each do |condition_image| %>
					<% if condition_image.variable?%>
						<%= link_to image_tag(condition_image, width: "70"), condition_image, onmouseover: "changeImage()", class: "picture" %>
					<% end %>
				<% end %>
			<% end %>
</div>







						<!-- START OF CAROUSEL VERSION FOR THE BOOK VIEWS-->
			<!--<div class="mt-2 moved">

						<% count = 0 %>
						<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
							<div class="carousel-inner">

											<% @book.condition_images.each do |condition_image| %>

												<% if count == 0 %>

												<div class="carousel-item active">
														<%= link_to image_tag(condition_image.variant(resize: "200x300")), condition_image, class: "d-block w-20" %>
												</div>
												<% count = count + 1 %>

											<% else %>

											<div class="carousel-item">
										<%= link_to image_tag(condition_image.variant(resize: "200x300")), condition_image, class: "d-block w-20" %>
											</div>

											<% count = count + 1 %>

										<% end %>
											<% end %>

										</div>


											<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
													<span class="carousel-control-prev-icon" aria-hidden="true"></span>
													<span class="sr-only">Previous</span>
												</a>
												<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
													<span class="carousel-control-next-icon" aria-hidden="true"></span>
													<span class="sr-only">Next</span>
												</a>

									</div>
			</div>-->
			<!-- END OF CAROUSEL VERSION FOR THE BOOK VIEWS-->
		</div>

		<!--END OF New Thumbnail -->
	<!--</div>


		<div class="row">-->
		<div class="col">
			<div class="card" >
				<div class="card-header text-center">
					<span style="font-size: 2em;">
						<strong>Info </strong>
					</span>
					<div class="text-right float-right">
						<% if logged_in? %>
							<% if current_user.id == @book.user_id %>
								<%= link_to "Edit", edit_book_path(@book), class: "btn btn-outline-primary mr-3" %>
								<% if current_user.id == @book.user_id %>
									<%= link_to "Conversations", messages_path, class: "btn btn-outline-primary mr-3" %>
								<% end %>
							<% else %>
								<% if current_user.id != @book.user_id %>
									<%= link_to "Contact Seller", conversations_path(sender_id: current_user.id, recipient_id: @book.user_id), method: 'POST', class: "btn btn-primary" %>
								<% elsif current_user.id == @book.user_id %>
									<%= link_to "Conversations", messages_path %>
								<% else %>
									<%= link_to "Log In To Buy", login, class: "btn btn-primary" %>
								<% end %>
							<% end %>
						<% else %>
							<%= link_to "Log In To Buy", login, class: "btn btn-primary" %>
						<% end %>
					</div>
				</div>


<!--#############################################
<#% if user_signed_in? && current_user.id != @trade.user_id %>
      <%#= link_to "Message #{@trade.user.name}", conversations_path(sender_id: current_user.id, recipient_id: @trade.user.id), method: 'post', class:"button is-link" %>
    <%# elsif user_signed_in? && current_user.id == @trade.user_id  %>
      <3%= link_to "Conversations", conversations_path %>
    <%# else %>

    <%#= link_to "Sign up to message #{@trade.user.name}", new_user_registration_path %>
    <%# end %>

 #############################################-->
				<div class="card-body" style="height: 400px; position: relative;">
					<div>
						<h3>
							<% if @book.condition == "Like New" %>
								<strong>Condition: </strong>
								<span class="px-2 my-2 text-success border border-success rounded" style="font-size: 1em; font-weight: bold; position: absolute; top: 12px; left: 200px;">
									<%= @book.condition %>
								</span>
							<% elsif @book.condition == "Good" %>
								<strong>Condition: </strong>
								<span class="px-2 my-2 text-warning border border-warning rounded" style="font-size: 1em; font-weight: bold; position: absolute; top: 12px; left: 200px;">
									<%= @book.condition %>
								</span>
							<% elsif @book.condition == "Acceptable" %>
								<strong>Condition: </strong>
								<span class="my-2 text-danger border border-danger rounded" style="font-size: 1em; font-weight: bold; position: absolute; top: 12px; left: 200px; margin-left: -35px;">
									<%= @book.condition %>
								</span>
							<% end %>
						</h3>
					</div>

					<div class="" style="">
						<div class="float-left">
							<h3><strong>Description: </strong></h3>
						</div>
						<div class="border rounded float-left px-2 pb-2" style="position: absolute; top: 100px; left: 20px; bottom: 60px; right: 20px; overflow: scroll;">
								<p class="pt-2"> <%= @book.description %></p>
						</div>
					</div>


					<div class="" style="position: absolute; bottom: 0; right: 0;">
					  	<div class="mt-auto p-2">
					  		<% if logged_in? %>
							<% if current_user.id == @book.user_id %>
								<%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-outline-primary"  %>
<!--							<%# else %>
								<%#= link_to "Contact Seller", book_path(@book), class: "btn btn-primary" %> -->
							<% end %>
						<% else %>
							<%= link_to "Log In To Buy", login, class: "btn btn-primary" %>
						<% end %>
					  	</div>
					</div>



							<!--	<p class="pt-2">-->
									<!-- function that loops images -->
									<%# @book.condition_images.each do |condition_image| %>
								      	<!--<div class="card-body m-2">
								      		<div class="row">
								      			<div class="col-auto">-->
								      				<%# if condition_image.variable? %>
														<%#= link_to image_tag(condition_image), condition_image %><!--<br />-->
													<%# end %>
								      			<!--</div>
								      		</div>
								   		</div>-->
									<%# end %>
									<!-- end of function -->
								<!--</p>-->




				</div>
			</div>
			<div class="isbnBlock">
				<span class="lead stuff" style="font-size: 1.15em;">
					ISBN-13: <%= @book.isbn13 %> <br />
					ISBN-10: <%= @book.isbn10 %>
				</span>
			</div>
		</div>
	</div>

			<!-- MULTIPLE IMAGES
				<div class="card-header text-center">
					<span style="font-size: 2em;"><strong>Images</strong></span>
				</div>
				<div class="card-body" style="height: 200px; position: relative;">
					<div class="d-none d-lg-block d-xl-block">
						<%#= @book.condition_images.each do |condition_image|%>
							<%# if condition_image.variable? %>
								<%#= link_to image_tag(condition_image), condition_image %><br />
							<%# end %>
						<%# end %>
					</div>
				</div>

			 End of Multiple Images -->

			<!-- <table class="w-100 my-3 clearfix" style="max-width: 600px;">
				<tr class="">
					<td class="float-right">
						<h3><strong>Author: </strong></h3>
					</td>
					<td class="">
						<h3><%= @book.author %></h3>
					</td>
				</tr>
				<tr class="">
					<td class="float-right">
						<h3><strong>ISBN: </strong></h3>
					</td>
					<td>
						<h3><%= @book.isbn13 %></h3>
					</td>
				</tr>
				<tr class="">
					<td class="float-right">
						<h3><strong>Condition: </strong></h3>
					</td>
					<td>
						<h3><%= @book.condition %></h3>
					</td>
				</tr>
				<tr class="">
					<td class="float-right">
						<h3><strong>Price: </strong></h3>
					</td>
					<td>
						<h3>$ <%= number_with_precision(@book.price, :precision => 2) %></h3>
					</td>
				</tr>
			</table>

			<div style="min-width: 600px;">
				<h3 class="float-left"><strong>Description: </strong></h3><br/><br/>
				<h5><%= @book.description %></h5>
			</div> -->

</div>