config/routes.rb
Rails.application.routes.draw do
  get 'errors/404'
  get 		'sessions/new'
  root 		'home#index'
  get 		'users/new'
  get     'edit',       to: 'users#edit'
  post    'edit',       to: 'users#update' 
  get     'users',      to: 'users#index'
  get 		'/signup',		to: 'users#new'
  post 		'/signup',		to: 'users#create'
  get 		'/login',		  to: 'sessions#new'
  post 		'/login',		  to: 'sessions#create'
  get 	'/logout',		to: 'sessions#destroy'
  get 'messages',       to: 'conversations#index'
  get 'inbox',			to: 'conversations#inbox'
  get 'conversations',	to: 'conversations#create'

  # for elasticsearch/searchkick
  #get 'search',         to: 'search#search'

  resources :users
  resources :books
  resources :account_activations, only: [:edit]
  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books do
    member do
      delete :delete_cover_image
      delete :delete_condition_image
    end
  end

  resources :books do
    collection do
      get :autocomplete 
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer text-light bg-secondary pt-4 mt-5" style=" position: relative; left:0; bottom:0; right:0; max-height: 190px; overflow: hidden;">
  <div class="container text-center text-md-left" >
    <div class="row pl-5">
      <div class="col md-6 mt-md-0 mt-3">
        <h5 class="text-uppercase">Disclaimer:</h5>
        <p>This website was created by students at George Mason University. Use at your own risk.</p>
      </div>
      <hr class="clearfix w-100 d-md-none pb-4">
      <% if logged_in? %>
        <div class="col-md-3 mb-md-0 mb-3">
          <h5 class="text-uppercase text-white-50">Navigation</h5>
          <ul class="list-unstyled">
            <li>
              <%= link_to "Home", root_path, class: "text-white" %>
            </li>
            <li>
              <%= link_to "All Listings", books_url, class: "text-white"  %> 
            </li>
            <li>
              <%= link_to "Users", '/users', class: "text-white"  %>
            </li>
          </ul>
        </div>
        <div class="col-md-3 mb-md-0 mb-3">
          <h5 class="text-uppercase text-white-50">Account</h5>
          <ul class="list-unstyled">
            <li>
              <%= link_to "View Profile", current_user, class: "text-white"  %>
            </li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete, class: "text-white"  %>
            </li>
          </ul>
        </div>
      <% else %>  <!-- Logged out-->
        <div class="col-md-3 mb-md-0 mb-3">
          <h5 class="text-uppercase">Navigation</h5>
          <ul class="list-unstyled">
            <li>
              <%= link_to "Home", root_path, class: "text-white"%>
            </li>
            <li>
              <%= link_to "All Listings", books_url, class: "text-white" %> 
            </li>
          </ul>
        </div>
        <div class="col-md-3 mb-md-0 mb-3">
          <h5 class="text-uppercase">Account</h5>
          <ul class="list-unstyled">
            <button type="button" class="btn btn-link text-light" style="text-decoration: none;" data-toggle="modal" data-target="#signInModal">
            Log In
            </button>
          </ul>
        </div>
      <% end %>
    </div>
    </div>
    <!-- Copyright -->
    <div class="footer-copyright text-white-50 bg-dark text-center py-3"> © 2018 Copyright:
      Brokebooks
    </div>
    <!-- Copyright -->
</footer>

app/views/layouts/_modal_signIn.html.erb
<div class="modal fade" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog  modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">
					Log in
				</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<% provide(:title, "Log in") %>
	      		<%= form_for(:session, url: login_path) do |f| %>
	        		<div class="form-group">
	          			<%= f.label :email %>
	          			<%= f.email_field :email, class: 'form-control', placeholder: "Email" %>
	        		</div>
	        		<div class="form-group">
	          			<%= f.label :password %>
	          			<%= f.password_field :password, class: 'form-control', placeholder: "Password" %>
	        		</div>
	        		<div class="d-flex align-content-start flex-wrap mt-5">
		        		<br>
		        		<%= f.label :remember_me, class: "checkbox inline" do %>
		        			<%= f.check_box :remember_me %>
		        			<span>Remember Me</span>
		        		<% end %>
	        		</div>
	      			<%= f.submit "Log in", class: "btn btn-lg btn-primary btn-block bottomPart" %>
    			<% end %>
			    <br> <p class="centered">New user? <%= link_to "Sign up now!", signup_path %></p> <br>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<style type="text/css">
	.colorful {
		outline-color: #f2f2f0;
		border-color: #f2f2f0;
		color: #f2f2f0;
	}

	.dropdown-item.whiteish:hover {
		background-color: #4c4c4c;
	}


</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<%= link_to "BrokeBooks", root_path, class: "navbar-brand" %>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" >
	    <span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">

	    	<% if current_page? controller:'home' %>
	      		<li class="nav-item active">
	      	<% else %>
	      		<li class="nav-item">
	      	<% end %>
	        	<%= link_to "Home", root_path, class: "nav-link" %> <span class="sr-only">(current)</span>
	      	</li>

	      	<% if current_page? '/books' %>
	      		<li class="nav-item active">
	      	<% else %>
	      		<li class="nav-item">
	      	<% end %>
	        	<%= link_to "All Listings", books_url, class: "nav-link" %>
	      	</li>

	      	<% if logged_in? %>

	      		<!-- If stmt here for dynamic nav links-->
				<li class="nav-item dropdown">
	      			<%= link_to "Users", '/users', class: "nav-link" %>
	      		</li>
	      		<li class="nav-item dropdown">
            		<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          				Account
        			</a>
        	  		<div class="dropdown-menu bg-dark font-light" aria-labelledby="navbarDropdown">
	          			<%= link_to "My Profile", current_user, class: "dropdown-item whiteish text-light" %>
	          			<%= link_to "Messages", messages_url, class: "dropdown-item whiteish text-light" %>

	          			<div class="dropdown-divider"></div>

	          			<%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item text-white whiteish" %>
	          		</div>
          		</li>

        	<% end %>
	    </ul>
	    <%= form_tag books_path, {:method => "get", class:"form-inline my-2 my-lg-0"} do %>
	    	<%= text_field_tag :search, 
	    		params[:search], 
	    		#id: 'books_search', uncomment for searchkick
	    		#autocomplete: :off, uncomment for searchkick
	    		class: "form-control mr-sm-2", 
	    		placeholder: "Search"%>
	    	<%= hidden_field_tag :direction, params[:direction] %>
	    	<%= hidden_field_tag :sort, params[:sort] %>
	    	<%= submit_tag "Search", class: "btn btn-outline-light my-2 my-sm-0" %>

				<!-- Individual login button start -->
								<ul class="navbar-nav mr-auto">

						<% if logged_in? %>
							<% next %>
						<% else %>
								<% if current_page? '/login' %> <li class="nav-item active"> <% else %> <li class="nav-item"> <% end %>
						<button type="button" class="btn btn-outline-light ml-2" style="text-decoration: none;" data-toggle="modal" data-target="#signInModal">
							Log In
						</button>
								</li>

						<% end %>
							</ul>

				<!-- Individual login button end -->
	    <% end %>

		<!-- Try for elastic search 
	    <%#= form_tag books_path, {:method => "get", class:"form-inline my-2 my-lg-0"} do %>
 			<p>
  				<%#= text_field_tag :search, params[:search] %>
  				<%#= hidden_field_tag :direction, params[:direction] %>
	    		<%#= hidden_field_tag :sort, params[:sort] %>
  				<%#= submit_tag "Go", name: nil %>
 			</p>
		<%# end %>  -->


	   <!-- <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
	      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
	    </form> -->
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <!-- <link rel="brokebooks icon" type="image/png" href="images/favicon.ico"/> -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- ************* Favicon ************* -->
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image" %>
  </head>

  <body>
  	<!-- DO NOT MOVE THIS: Renders the navigation bar on each page. -->
    <%= render 'layouts/navbar' %>


  	<div class="container mt-3">
  		<div id="content-container">
  		    <% flash.each do |message_type, message| %>
  		    	 <div class="alert alert-<%= message_type %>"><%= message %></div>
  		    <% end %>
  		    <%= yield %>
  		</div>
  	</div>

    <!-- This renders the login modal -->
    <%= render 'layouts/modal_signIn' %>  
    <!-- This renders the footer on all pages but /messages -->
    <% if !current_page?("/messages") and !current_page?(@conversations_path) %>
      <%= render 'layouts/footer' %>
    <% end %>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
   
   <script>
    function connectToBookAPI() {
      var isbn10 = document.getElementById("isbn10").value.trim(), isbn13 = document.getElementById("isbn13").value.trim();
      if ((isbn10 == "" && isbn13 == "") || (isbn10.length != 10 && isbn13.length != 13)) {
        isFillable("block");
        return;
      }
      checkDigits(isbn13.length == 13 ? isbn13 : isbn10) ? getBook(isbn13.length == 13 ? isbn13 : isbn10) : isFillable("block");
    }
    function checkDigits(isbn) {
      if(isbn.length == 13 && isbn.substring(0,3).localeCompare("978") != 0) {
        return false;
      }
      for(i = 0; i < isbn.length; i++) {
        if(isbn.charCodeAt(i) < 48 || isbn.charCodeAt(i) > 57) {
          return false;
        }
      }
      return true;
    }
    function getBook(isbn) {
      // return fetch("https://www.googleapis.com/books/v1/volumes?q=isbn:" + isbn + "&key=AIzaSyAfGsYAIletzGKRLE46MhaZuXA26K2LDqA")
      //   .then(response => response.json())
      //   .then((data) => {
      //     bookInfo = data["items"];
      //   })
      //   .catch((err) => {
      //     isFillable("block");
      //   });
      fetch("https://www.googleapis.com/books/v1/volumes?q=isbn:" + isbn + "&key=AIzaSyAfGsYAIletzGKRLE46MhaZuXA26K2LDqA")
        .then(function(response) {
          return response.json();
        })
        .then(function(myJson) {
          setValues(myJson['items']);
          swapIsbns();
        });
    }
    function setValues(bookInfo) {
      if(bookInfo == undefined || bookInfo == null) {
        isFillable("block");
      }
      else {
        isFillable("none");
        document.getElementById("title").value = bookInfo[0]['volumeInfo']['title'];
        document.getElementById("author").value = getAuthors(bookInfo[0]['volumeInfo']['authors']);
        document.getElementById("isbn13").value = getIsbn(bookInfo[0]['volumeInfo']['industryIdentifiers'], "ISBN_13"); 
        document.getElementById("isbn10").value = getIsbn(bookInfo[0]['volumeInfo']['industryIdentifiers'], "ISBN_10");  
        document.getElementById("description").value = bookInfo[0]['volumeInfo']['description'];
      }
    }
    function isFillable(msg) {
      document.getElementById("unableToFill").style.display = msg;
    }
    function getIsbn(isbns, type) {
      if(isbns.length == 1) {
        return isbns[0]['type'].localeCompare(type) == 0 ? isbns[0]['identifier'] : "";
      }
      return isbns[0]['type'].localeCompare(type) == 0 ? isbns[0]['identifier'] : isbns[1]['identifier'];
    } 
    function getAuthors(authors) {
      if(authors.length == 1) {
        return authors[0];
      }
      var str = "";
      authors.forEach(function(author) {
        str += ", " + author;
      });
      return str.substring(2);
    }
    function clearAllBookFields() {
      isFillable("none");
      document.getElementById("title").value = "";
      document.getElementById("author").value = "";
      document.getElementById("isbn13").value = "";
      document.getElementById("isbn10").value = "";
      document.getElementById("description").value = "";
      document.getElementById("price").value = "";
    }
    function swapIsbns() {
      let isbn10 = document.getElementById("isbn10"), isbn13 = document.getElementById("isbn13");
      isbn10.value = isbn10.value == undefined ? "" : isbn10.value;
      isbn13.value = isbn13.value == undefined ? "" : isbn13.value;
      if(isbn10.value.length == 13 && isbn13.value.length == 10) {
        let temp = isbn10.value;
        isbn10.value = isbn13.value;
        isbn13.value = temp;
      }
      else if((isbn10.value == 13 && isbn13.value == 0) || (isbn13.value == 10 && isbn10.value == 0)) {
        if(isbn10.value == 13) {
          isbn13.value = isbn10.value;
          isbn10.value = "";
          return;
        }
        isbn10.value = isbn13.value;
        isbn13.value = "";
      }
    }
    function clearUserPasswordFields() {
      document.getElementById("pwd").value = "";
      document.getElementById("pwdValidation").value = "";
    }
   </script>

   </body>
</html>